#!/usr/bin/env bash

basedir="$HOME/Pictures/Screenshots"

mkdir -p $basedir

if [ ${1} != "-s" ]
then
    prms="-window root"
fi

filepath="$basedir$(date '+%Y-%m-%d_%H-%M-%S')_screenshot.png"
import $prms $filepath
xclip -selection clipboard -target image/png -i < $filepath
